import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import Cart from "./types/Cart";
import Header from "./components/Header";
import { CartProvider } from "./contexts/CartContext";
import "./globals.css";

const rubikFont = Rubik({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <CartProvider>
        <body className={`${rubikFont.className} antialiased`}>
          <Header />
          {children}
        </body>
      </CartProvider>
    </html>
  );
}
