import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";

const rubikFont = Rubik({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rubikFont.className} antialiased`}>
        <header className="bg-blue-900 flex w-full h-20 border-bottom shadow-xl"></header>
        {children}
      </body>
    </html>
  );
}
